#!/usr/bin/env bash

# TODO: alias command for switching between PS1 versions (simple, full)
# TODO: terminal color adjustment

function prompt_command {
  local EXIT="$?"

  PS1="\[\e[0m\]\n"
  if [ $EXIT != 0 ]; then
    PS1+="\[\e[1;97;41m\]"
  else
    PS1+="\[\e[1;97;42m\]"
  fi
  PS1+="$(printf ' %3s ' $EXIT)\[\e[0;93;40m\] \t \[\e[0m\]j:\j "

  local PSCHAR='\$'
  if [ $(id -u) -eq 0 ]; then
    PS1+="\[\e[1;92;41m\]\u@\h"
    PSCHAR="\e[1;91m$PSCHAR"
  else
    PS1+="\[\e[1;92m\]\u@\h"
  fi
  PS1+="\[\e[0;1;34m\] \w"

  GIT_PS1_SHOWDIRTYSTATE=1      # '*' unstaged, '+' staged
  GIT_PS1_SHOWSTASHSTATE=1      # '$' Something is stashed
  GIT_PS1_SHOWUNTRACKEDFILES=1  # '%' There are untracked files
  GIT_PS1_SHOWUPSTREAM=auto     # '<' behind upstream, '>' ahead, '<>' diverged, '=' same
  GIT_PS1_SHOWCOLORHINTS=1      

  __git_ps1 "${PS1}\[\e[0m\]" "\[\e[0m\]"

  PS1+="\n${PSCHAR}\[\e[0m\e[5 q\] "
}

PROMPT_COMMAND="prompt_command;${PROMPT_COMMAND}"
